# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails" # Commented out if you don't need it

gem 'sinatra'
gem 'savon'  # Only if you are going to use SOAP  🚀
gem 'pg'
gem 'dotenv'
gem 'securerandom'
gem 'sinatra-cross_origin'  # To enable CORS in Sinatra
gem 'rackup'
gem 'puma'